### ISSUE TITLE
Bug: `$generateHtmlFromNodes` doesn't work inside of `registerUpdateListener` and `editorState.read`

### ISSUE THREAD

**Issue by obask** [facebook/lexical#2325]
I can't use `$generateHtmlFromNodes` the same way as I use `$convertToMarkdownString` to store the editor state somewhere.

```
Uncaught Error: Cannot use method in read-only mode.
    at errorOnReadOnly (Lexical.dev.js:5113:1)
    at new LexicalNode (Lexical.dev.js:5886:1)
    at new ElementNode (Lexical.dev.js:6613:1)
    at new ParagraphNode (Lexical.dev.js:8153:1)
    at ParagraphNode.clone (Lexical.dev.js:8159:1)
    at $cloneWithProperties (LexicalSelection.dev.js:23:1)
    at $appendNodesToHTML (helpers.ts:128:1)
    at $generateHtmlFromNodes (helpers.ts:113:1)
```

And if I run it outside of `editorState.read` I'm getting:

```
Uncaught Error: Unable to find an active editor state. State helpers or node methods can only be used synchronously during the callback of editor.update() or editorState.read().

```

Lexical version: 0.3.0

## Steps To Reproduce

1. add a plugin listening to editor changes
2. try to serialize state

Link to code example:
```
function MyFunPlugin() {
    const [editor] = useLexicalComposerContext()

    // @ts-ignore
    editor.registerUpdateListener(({editorState}) => {
        editorState.read(() => {
            const tmp = $generateHtmlFromNodes(editor)
            console.log(tmp)
        })
    })
}

export default function RtfEditor() {
    return (
        <LexicalComposer initialConfig={editorConfig}>
            <MyFunPlugin />
// ...
```

## The expected behavior

I can serialize editor state to HTML to store it in a local file.

PS it would be nice to update docs too, since the given example doesn't work:
https://lexical.dev/docs/concepts/serialization#lexical---html

**Comment by trueadm** [comment]
This is because `EditorState` is independent of `Editor, but in order to generate HTML we need to have knowledge of all the Lexical nodes in a given editor. You can instead use `editor.update` instead of `editorState.read`. If an update doesn't actually update anything, it gets discarded as an optimization feature :)

**Comment by luctc-dev** [comment]
I think this issue is fixed, right? Can you close this? @obask

**Comment by naabbassi** [comment]
I have still the same problem with serialize Lexical to HTML

**Comment by almazkaliyev** [comment]
My solution (combined with `OnChangePlugin`):
```typescript
  const [html, setHtml] = useState<string>('')
  
  const onChange = (editorState: EditorState, editor: LexicalEditor) => {
    editor.update({
      const raw = $generateHtmlFromNodes(editor, null)
      setHtml(raw)
    })
  }

  return <OnChangePlugin onChange={onChange} ignoreSelectionChange />
```

`ignoreSelectionChange` because i wanna serialize all the state and without this flag my app is freezing if any tables are there

**Comment by pgmccullough** [comment]
> My solution (combined with `OnChangePlugin`):
> 
> ```ts
>   const [html, setHtml] = useState<string>('')
>   
>   const onChange = (editorState: EditorState, editor: LexicalEditor) => {
>     editor.update({
>       const raw = $generateHtmlFromNodes(editor, null)
>       setHtml(raw)
>     })
>   }
> 
>   return <OnChangePlugin onChange={onChange} ignoreSelectionChange />
> ```
> 
> `ignoreSelectionChange` because i wanna serialize all the state and without this flag my app is freezing if any tables are there

Thanks so much for this! Don't know if the update method changed since then, but you do now have to do it as a callback function:

```
  const onChange = (editorState: EditorState, editor: LexicalEditor) => {
    editor.update(() => {
      const raw = $generateHtmlFromNodes(editor, null)
      setHtml(raw)
    })
  }
```

**Comment by hjaber** [comment]
https://github.com/facebook/lexical/issues/2587#issuecomment-1449165003

```tsx
editor.getEditorState().read(() => $generateHtmlFromNodes(editor, null)
```

using in combo with ref/onSubmit handler
```tsx
const editorRef = useRef(null);
<Editor ref={editorRef} />;
```

```tsx
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const editor = editorRef.current;
    const htmlString = editor
      .getEditorState()
      .read(() => $generateHtmlFromNodes(editor, null));
    console.log(htmlString);
  };
 ```

**Comment by samadfullstack** [comment]
```import { useLexicalComposerContext } from "@lexical/react/LexicalComposerContext";
import { $generateHtmlFromNodes } from "@lexical/html";
import { useEffect } from "react";

const HtmlGeneratorPlugin = () => {
  const [editor] = useLexicalComposerContext();

  function printHtml() {
    editor.update(() => {
      const html = $generateHtmlFromNodes(editor, null);
      console.log(html);
    });
  }

  useEffect(() => {
    editor.registerUpdateListener(() => {
      printHtml();
    });
  }, [editor]);

  return null;
};

export default HtmlGeneratorPlugin;
```

**Comment by samandar113** [comment]
@samadfullstack can't get how you store html string
