### ISSUE TITLE
Bug: Selecting text by triple clicking also selects the following top level nodes, up to and including the next text node.

### ISSUE THREAD

**Issue by AaronGazzola** [facebook/lexical#2660]
Triple clicking a text node in the lexical playground selects the parent node and the following top level nodes up to and including the next text node.

The following image shows the resulting editor state after triple clicking the first paragraph:
![Editor state after triple-clicking a paragraph node that is followed by a decorator node and a paragraph node](https://user-images.githubusercontent.com/75453092/179881639-55af7ce1-7996-4dab-ad6e-d20386d5ccb0.png)

This causes a breaking bug where the page becomes unresponsive if the block format drop down menu is used to format content that was selected this way, if the content contains a decorator node.

The following image is the unresponsive playground after triple-clicking the text above a YouTube node and then using the dropdown block format menu to format the content as heading 3:
![Unresponsive playground](https://user-images.githubusercontent.com/75453092/179878059-0fcaec85-5ba7-4b33-93cc-ae38ffb2bf8a.png)

Lexical version: 0.3.7

## Steps To Reproduce

1. Insert a top level decorator node into the lexical playground, such as a YouTube node
2. Create paragraph nodes with text content above and below the top level decorator node 
3. Select the text in the first paragraph node by triple clicking (the tree view plugin should show that the bottom paragraph node is also selected, while the text in the editor is not highlighted)
5. Use the dropdown block format menu to change the format to any of the options, eg. Heading 1

Link to code example: https://playground.lexical.dev/

## The current behavior
Selecting text by triple clicking also selects the following top level nodes, up to and including the next text node.

## The expected behavior
When text is selected by triple clicking, only the clicked node should be selected

**Comment by thegreatercurve** [comment]
I was able to replicate this bug a few days ago, but since the latest release this seems to have been fixed now. I am able to apply block styles even when the selection contains a decorator node without crashing the editor.

**Comment by acywatson** [comment]
> I was able to replicate this bug a few days ago, but since the latest release this seems to have been fixed now. I am able to apply block styles even when the selection contains a decorator node without crashing the editor.

I'm still not sure this is behaving correctly - triple click behavior varies amongst browser, but it doesn't seem like we should be selecting everything between the triple-clicked line and the next text node. For instance, if you do this an then hit delete, you also delete the DecoratorNode.

**Comment by AaronGazzola** [comment]
> I was able to replicate this bug a few days ago, but since the latest release this seems to have been fixed now. I am able to apply block styles even when the selection contains a decorator node without crashing the editor.

In Chrome and Safari in the latest lexical playground, triple clicking a text node selects both the top level parent of the clicked text node and the top level parent of the next text node. However the selection is only highlighted for the text node that was clicked. Applying block level styling in this state results in **both** parent nodes being styled.

**Comment by acywatson** [comment]
More reading on this chromium bug led me to the a w3c Selection API spec discussion:

https://github.com/w3c/selection-api/issues/70

Which led me to CKEditor also dealing with this exact same issue a while back:

https://github.com/ckeditor/ckeditor4/issues/484
https://github.com/ckeditor/ckeditor4/issues/3118

It looks like they solved this problem by just normalizing selection so that, except for some special cases, it just can't be focused on an element node/on the zero offset of a text node. We might be able to take an approach like that.

In the past, we have taken the position that this is an "upstream issue" or a "browser quirk" and that we should fix this type of thing by changing how our library handles applying changes (formatting, specifically) to a selected range. This case sort of shows how that approach falls short. I think one of most useful things about Lexical is that we try to make weird quirks like this implementation details of the library, so I'm inclined to say we should fix this universally with a similar Selection normalization approach.

Trade-off will be that some different, but I think very uncommon edge case behaviors, may not work as expected.

**Comment by husseinraoouf** [comment]
@acywatson checking on the status of this issue
