### ISSUE TITLE
Bug: Pasting a paragraph breaks `trimTextContentFromAnchor`

### ISSUE THREAD

**Issue by GiacomoRandazzo** [facebook/lexical#3773]
Lexical version: 0.7.6

## Steps To Reproduce

1. Open Lexical Playground with the "Max Length" setting on: https://playground.lexical.dev/?isMaxLength=true
2. Paste a paragraph, where `text/html` in the clipboard is a `<p>` tag. (You can copy the entire first paragraph at https://lexical.dev/docs/intro)
3. The text is not pasted. `trimTextContentFromAnchor`, called by `MaxLengthPlugin`, crashes as it attempts to remove the root node.

Note that, at https://lexical.dev/docs/intro:
- if you copy the title along with the first paragraph, it will be pasted correctly in the editor
- if you copy only a portion of the paragraph, it will be pasted correctly in the editor

**Comment by pratik9333** [comment]
Can I work on this bug?

**Comment by GiacomoRandazzo** [comment]
That would be great! #3775 might be related.

**Comment by pratik9333** [comment]
Damn, how are you guys able to notice such bugs? good job!

**Comment by pratik9333** [comment]
Are there any volunteers who can assign me this issue?

**Comment by thegreatercurve** [comment]
Feel free @pratik9333

**Comment by SalmanWasiKhan** [comment]
@pratik9333 Is there any progress on this issue?

**Comment by 777PolarFox777** [comment]
I believe that this line cause the error https://github.com/facebook/lexical/blob/501f5f5af882d9c702372399a74d5fa5d0eea67d/packages/lexical-playground/src/plugins/MaxLengthPlugin/index.tsx#L43

It looks like this method doesn't work correctly, I'm seeing some Nodes in NodeMap having __next field that points to non-existing nodes and that's where the error occurs: `createChildrenArray: node does not exist in nodeMap`

**Comment by alexkalinins** [comment]
@777PolarFox777 Yes it is caused by `$restoreEditorState`.

The same error also appears when pressing enter after reaching the input limit.

**Comment by CanRau** [comment]
> @777PolarFox777 Yes it is caused by `$restoreEditorState`.
> 
> The same error also appears when pressing enter after reaching the input limit.

facing the same issue, interestingly I can't reproduce it in the playground though 🤷🏼 



> I believe that this line cause the error
> 
> https://github.com/facebook/lexical/blob/501f5f5af882d9c702372399a74d5fa5d0eea67d/packages/lexical-playground/src/plugins/MaxLengthPlugin/index.tsx#L43
> 
> It looks like this method doesn't work correctly, I'm seeing some Nodes in NodeMap having __next field that points to non-existing nodes and that's where the error occurs: `createChildrenArray: node does not exist in nodeMap`

Tried to replace it with `editor.setEditorState(prevEditorState)` but then realized that my `prevEditorState` contains non-existing `__next` nodes

**Comment by CanRau** [comment]
Has actually been fixed in https://github.com/facebook/lexical/pull/4871
Just tested and works as expected 🥳

So this issue can be closed I guess

**Comment by giacomoran** [comment]
It's still not working for me.

Lexical: 0.12.2 (assuming Lexical Playground uses the latest version)
Chrome on MacOS

https://github.com/facebook/lexical/assets/8596184/4194349e-7f63-406d-a32d-2206a3c4b87c

**Comment by khsily** [comment]
> It's still not working for me.
> 
> Lexical: 0.12.2 (assuming Lexical Playground uses the latest version) Chrome on MacOS
> 
>  Screen.Recording.2023-09-14.at.22.26.17.mp4

I made a PR for this issue. Please check #5020
