### ISSUE TITLE
AutoLink should also respect the default behavior of toogle link command

### ISSUE THREAD

**Issue by WinmezzZ** [facebook/lexical#4674]
AutoLink should also respect the default behavior of toogle link.

AutoLink Plugin is a nice plugin when we need transform a http url to an html link element, but sometimes we want to cancel the link for an url, just for showing but not allowed to click

https://github.com/facebook/lexical/assets/40154766/f412ca3e-b404-41b2-afc6-e26dfc2002e8

**Comment by ankitpawar03** [comment]
I want to work on this issue please assign me this.

**Comment by thegreatercurve** [comment]
@ankitpawar03 Happy for you to take a look. Assigned it to you.

**Comment by ankitpawar03** [comment]
> @ankitpawar03 Happy for you to take a look. Assigned it to you.

I ran it on my local system and searched on the source code but couldn't get how to disable auto-link, can you help me with it?

**Comment by ankitpawar03** [comment]
> @ankitpawar03 Happy for you to take a look. Assigned it to you.

Thank you for giving me this opportunity, but I am unable to resolve this issue yet, so I am unassigning myself from this...

**Comment by Infinity8sailor** [comment]
@thegreatercurve, Hey, I was working on this issue but realised that even if we toggle the auto link, it will automatically going to consider it again. I mean, we might need to consider it auto-link for the first time but somehow need to ignore it for the second time.

**Comment by jagan-blip** [comment]
@thegreatercurve, Hi, I have found a way to fix this issue. We can add an hidden character infront of the text so the link is no longer valid although You can't toggle it but you can fix the autolink issue.

```javascript
editor.update(() => {
                    const selection = $getSelection();

                    if ($isRangeSelection(selection)) {
                      const node = getSelectedNode(selection);
                      const parent = node.getParent();

                      if (parent.__type === "autolink") {
                        const hiddenCharacter = "\u200C";
                        node.setTextContent(
                          hiddenCharacter + node.getTextContent()
                        );
                        parent.remove();
                        $wrapNodes(selection, () =>
                          $createParagraphNode().append(node)
                        );
                      }
                      
                    }
                  });


```
This prevents the autolink from recognizing this as a valid url.

**Comment by hazirmagron** [comment]
> @thegreatercurve, Hey, I was working on this issue but realised that even if we toggle the auto link, it will automatically going to consider it again. I mean, we might need to consider it auto-link for the first time but somehow need to ignore it for the second time.

Have this approach been given up on?

It is how I would expect it to work. Not having the ability to have both 1) auto link copy/pasted links and 2) remove the anchor is poor UX. Ideally both is possible through this approach.

**Comment by juliana-samoilenko** [comment]
It looks like the problem was solved here
https://github.com/facebook/lexical/issues/5607

**Comment by sherkhane-vivek** [comment]
> It looks like the problem was solved here [#5607](https://github.com/facebook/lexical/issues/5607)
> 
> is that right?

Seems like it has not been resolved yet, the issue still persists even in latest version of lexical (0.40.0)

**Comment by etrepum** [comment]
The functionality added in #5607 works, it’s unclear what you tried to do but if you toggle an auto link it should stay unlinked. If you think it doesn’t work file a new issue with a full reproduction so it can be investigated.

**Comment by sherkhane-vivek** [comment]
> The functionality added in [#5607](https://github.com/facebook/lexical/issues/5607) works, it’s unclear what you tried to do but if you toggle an auto link it should stay unlinked. If you think it doesn’t work file a new issue with a full reproduction so it can be investigated.

Here is the sandbox for it: [https://codesandbox.io/p/devbox/great-nova-5q24ql?workspaceId=ws_Jvy6fyT9vyUe3GAVZbe7xE](https://codesandbox.io/p/devbox/great-nova-5q24ql?workspaceId=ws_Jvy6fyT9vyUe3GAVZbe7xE)

When typing in https://www.google.com, the text gets converted to link but I cannot toggle it back to normal text.

**Comment by etrepum** [comment]
You're using Lexical 0.4.0 released 3 years ago, the current version is 0.40.0.

**Comment by sherkhane-vivek** [comment]
> You're using Lexical 0.4.0 released 3 years ago, the current version is 0.40.0.

It still does not work 

sandbox with latest package version: https://codesandbox.io/p/devbox/great-nova-5q24ql

**Comment by etrepum** [comment]
Sorry, closed issues on GitHub are not a support channel. This functionality works if set up correctly, you can observe it working in the playground.

**Comment by sherkhane-vivek** [comment]
> Sorry, closed issues on GitHub are not a support channel. This functionality works if set up correctly, you can observe it working in the playground.

Checked the code of playground on github, it is similar to what I provided as sandbox and still it is failing. Unfortunate.
