### ISSUE TITLE
Bug: Can't delete lexical table at selection

### ISSUE THREAD

**Issue by MarcoColiaAtFiftyDeg** [facebook/lexical#7048]
After a table creation, is impossible to delete it at selection, remain always the first cell and is undeletable (see video below)

https://streamable.com/sh7efv

Lexical version: @lexical/table": "0.19.0

## Steps To Reproduce

1. Create a table
2. Select it and delete with backspace command

Link to code example:

```
const handleInsertTable = () => {
        editor.update(() => {
            const selection = $getSelection();

            if ($isRangeSelection(selection)) {
                const tableNode = $createTableNodeWithDimensions(Number(rows), Number(cols));

                $insertNodeToNearestRoot(tableNode);
                const paragraphNode = $createParagraphNode();

                $insertNodeToNearestRoot(paragraphNode);
                selection.insertParagraph();
            }
        });
    };


const handleTableDeletion = (): boolean => {
        let wasHandled = false;

        editor.update(() => {
            const selection = $getSelection();

            if ($isRangeSelection(selection)) {
                const anchorNode = selection.anchor.getNode();
                const focusNode = selection.focus.getNode();

                const anchorTableNode = anchorNode.getTopLevelElementOrThrow();
                const focusTableNode = focusNode.getTopLevelElementOrThrow();

                if ($isTableNode(anchorTableNode) && anchorTableNode === focusTableNode) {
                    anchorTableNode.remove();
                    wasHandled = true;
                }
            }
        });

        return wasHandled;
    };

useEffect(() => {
        return mergeRegister(
            editor.registerUpdateListener(({ editorState }) => {
                editorState.read(() => {
                    updateToolbar();
                });
            }),
            editor.registerCommand(KEY_BACKSPACE_COMMAND, handleTableDeletion, COMMAND_PRIORITY_EDITOR)
        );
        
    }, [updateToolbar, editor]);
```

So there's actually something that i missed?

**Comment by ivailop7** [comment]
We have fixed a lot of table issues, update to the latest Lexical version, which is 0.23.1 and try again.

If you can't reproduce the issue in the playground, it's probably not the library.

**Comment by justoverclockl** [comment]
but i cant install different version of lexical and table, isn't it?

**Comment by MarcoColiaAtFiftyDeg** [comment]
> We have fixed a lot of table issues, update to the latest Lexical version, which is 0.23.1 and try again.
> 
> If you can't reproduce the issue in the playground, it's probably not the library.

i've updated to latest version but i still cant delete the table if i select it

**Comment by MarcoColiaAtFiftyDeg** [comment]
ok after some try, now seems to work with latest version of all libraries.
